# List 1 - Codes
list_codes = [
    "Q305",
    "Q311",
    "Q312",
    "Q313",
    "T801I",
    "T802I",
    "T803I",
    "T804I",
    "T805I",
    "T801",
    "T802",
    "T803",
    "T804",
    "T805",
    "V301I",
    "V305",
    "V403",
    "V4062",
    "V4065",
    "f071",
    "f3113I",
    "f3213I",
    "p311",
    "p312",
    "p313",
    "p403",
    "p4055",
    "p4072",
    "t311",
    "t312",
    "t313",
    "t4012",
    "t4015",
    "t4018",
]

# List 2 - Descriptions
list_descriptions = [
    "Einspritzstrom",
    "Nachdruck Volumenstrom",
    "Nachdruck Volumenstrom",
    "Nachdruck Volumenstrom",
    "Zylinderheizzone 1",
    "Zylinderheizzone 2",
    "Zylinderheizzone 3",
    "Zylinderheizzone 4",
    "Zylinderheizzone 5",
    "Zylinderheizzone 1",
    "Zylinderheizzone 2",
    "Zylinderheizzone 3",
    "Zylinderheizzone 4",
    "Zylinderheizzone 5",
    "Schneckenvolumen",
    "Umschaltvolumen",
    "Dosiervolumen",
    "Massepolster",
    "Umschaltvolumen",
    "Zyklenzähler",
    "KurvenMesswerte_i",
    "KurvenMesswerte_ii",
    "Stützpunkt 1",
    "Stützpunkt 2",
    "Stützpunkt 3",
    "Staudruck",
    "maximaler Spritzdruck",
    "Umschaltspritzdruck",
    "Rampenzeit bis Stützpunkt 1",
    "Rampenzeit bis Stützpunkt 2",
    "Rampenzeit bis Stützpunkt 3",
    "Zykluszeit",
    "Dosierzeit",
    "Einspritzzeit",
]

# List 3 - Types
list_types = [
    "soll",
    "soll",
    "soll",
    "soll",
    "ist",
    "ist",
    "ist",
    "ist",
    "ist",
    "soll",
    "soll",
    "soll",
    "soll",
    "soll",
    "Dosiervolumen ist",
    "soll",
    "soll",
    "ist",
    "ist",
    "ist",
    "MeasuringCharts 1",
    "MeasuringCharts 2",
    "Nachdruckhöhe 1 soll",
    "Nachdruckhöhe 2 soll",
    "Nachdruckhöhe 3 soll",
    "soll",
    "ist",
    "ist",
    "Nachdruckzeit 1 soll",
    "Nachdruckzeit 2 soll",
    "Nachdruckzeit 3 soll",
    "ist",
    "ist",
    "ist",
]


# Create a dictionary mapping descriptions to codes and types
descriptions = {
    desc: {"code": code, "type": typ}
    for desc, code, typ in zip(list_descriptions, list_codes, list_types)
}


#
labels_time_series = {
    "Zeit": "0",
    "Einspritzdruck soll": "1",
    "Einspritzdruck ist": "2",
    "Schneckenvolumen": "3",
    "Volumenstrom": "4",
    "State": "5",
}

labels_single_metrics = {
    "Dosiervolumen": "V301I",
    "Massepolster": "V4062",
    "Umschaltvolumen": "V4065",
    "Maximaler Spritzdruck": "p4055",
    "Umschaltspritzdruck": "p4072",
    "Zykluszeit": "t4012",
    "Dosierzeit": "t4015",
    "Einspritzzeit": "t4018",
}

labels_quality_metrics = {
    # "Losnummer": 0,
    "Durchmesser_001": 1,
    "Abstand_001": 2,
    "Winkel_001": 3,
    "Winkel_002": 4,
    "Abstand_002": 5,
    "Parallelität_001": 6,
    "Durchmesser_002": 7,
    "Konzentrizität_002": 8,
    "Gewicht": 9,
}
